eiffel-community/eiffel-remrem-publish

- src/main/java/com/ericsson/eiffel/remrem/publish/helper/RMQHelper.java
fixed eiffel-remrem-publish/issues/23
> add clean up method for closing rabbitmq connection

- .gitignore
- build.gradle
- src/integration-test/resources/application.yml
- src/main/java/com/ericsson/eiffel/remrem/publish/App.java
- src/main/java/com/ericsson/eiffel/remrem/publish/cli/CLI.java
- src/main/java/com/ericsson/eiffel/remrem/publish/config/PropertiesConfig.java
- src/main/java/com/ericsson/eiffel/remrem/publish/helper/RMQHelper.java
- src/main/java/com/ericsson/eiffel/remrem/publish/service/MessageService.java
- src/main/java/com/ericsson/eiffel/remrem/publish/service/MessageServiceRMQImpl.java
- src/main/resources/application.yml
after building with ./gradlew build
run java -jar remrem-publish.0.1.0.war -f <file containing events to publish>
the file should have a list of events between [ ]
the message bus used is  mb101-eiffel010.lmera.ericsson.se
If it needs to be change modify src/main/resources/application.yaml
> add cli functionality to publish component

- CHANGELOG.md
- build.gradle
- src/main/java/com/ericsson/eiffel/remrem/publish/cli/CLI.java
- src/main/java/com/ericsson/eiffel/remrem/publish/cli/CliOptions.java
- src/main/java/com/ericsson/eiffel/remrem/publish/helper/RemremJarHelper.java
- src/main/java/com/ericsson/eiffel/remrem/publish/listener/DirectoryWatchService.java
- src/main/java/com/ericsson/eiffel/remrem/publish/listener/Service.java
- src/main/java/com/ericsson/eiffel/remrem/publish/listener/SimpleJarDirectoryWatchService.java
- src/main/resources/application.yml
- src/test/java/com/ericsson/eiffel/remrem/publish/service/JarPathImplUnitTest.java
**Dynamic jar loading:**
Two ways we can add jar
1) Using CLI (Command Line Interface) provide the **"jp"** (Jar Path) Parameter
2) Using application.yml provide the jar path
Using this added functionality we can inject messaging library.
> Added functionality for dynamic jar loading.

- CHANGELOG.md
- build.gradle
Also updated some old and specifically stated version on some that
missed it.
> Removed unused dependencies.

- CHANGELOG.md
- build.gradle
- src/integration-test/java/com/ericsson/eiffel/remrem/publish/controller/ProducerControllerIntegrationTest.java
- src/main/java/com/ericsson/eiffel/remrem/publish/cli/CliOptions.java
- src/main/java/com/ericsson/eiffel/remrem/publish/config/PropertiesConfig.java
- src/main/java/com/ericsson/eiffel/remrem/publish/controller/ProducerController.java
- src/main/java/com/ericsson/eiffel/remrem/publish/helper/RMQHelper.java
- src/main/java/com/ericsson/eiffel/remrem/publish/service/MessageService.java
- src/main/java/com/ericsson/eiffel/remrem/publish/service/MessageServiceRMQImpl.java
- src/main/java/com/ericsson/eiffel/remrem/publish/service/PublishResultItem.java
- src/main/java/com/ericsson/eiffel/remrem/publish/service/SendResult.java
- src/test/java/com/ericsson/eiffel/remrem/publish/service/MessageServiceRMQImplUnitTest.java
Added code for generating status code for events in Remrem publish
> Add status code for output events

- index.html
Added status code changes in publish output
> Added status code documentation for Publish

- CHANGELOG.md
- build.gradle
- Updated the semantics version to support EiffelEvents from eiffel repo topic-drop4 branch
> Updated the semantics version

- index.html
Added LDAP authentication information and status codes information
> Improvemnts in REMReM documentation(eiffel-remrem-publish)

- index.html
updated documentation related to versions endpoint functionality.
> added documentation for versions endpoint

- index.html
Update documention with valid InputEventType in input JSON
> Update documention with valid InputEventType in input JSON

- index.html
Examples, that don't work correct, were updated.
> Updated non-workable examples in documentation

- CHANGELOG.md
- build.gradle
- publish-common/src/main/resources/config.template.properties
- publish-service/src/main/java/com/ericsson/eiffel/remrem/publish/config/DisabledSecurityConfig.java
- publish-service/src/main/java/com/ericsson/eiffel/remrem/publish/config/SecurityConfig.java
Added functionality to disable authentication in publish if required
> Added functionality to disable authentication in publish

- build.gradle
Updated remrem-semantics version to the latest version 0.3.6
> Updated remrem-semantics version to the latest version 0.3.6

- CHANGELOG.md
- build.gradle
Changed version in build.gradle to 0.5.2 and modified changelog
* 0.5.2 jitpack release was not at done so changed version to 0.5.2 from 0.5.3 in build.gradle
> Changed version in build.gradle to 0.5.2 and modified changelog

- CHANGELOG.md
- build.gradle
- publish-cli/build.gradle
Added logback support
Uplifted eiffel-remrem-protocol-interface version 0.0.5 to 0.0.7
> added logback support

- index.html
- logback/logback-sample.xml
- stylesheets/stylesheet.css
Added logging documentation
page size increased 640px to 1200px, for better view
Little bit modifications on documentation
> added documentation for the logging

- CHANGELOG.md
- build.gradle
- publish-common/src/main/resources/config.template.properties
Added jasypt-spring-boot-starter dependency to support open text password encryption
> Added jasypt spring boot dependency to support open text password encryption

- CHANGELOG.md
- build.gradle
- publish-service/src/main/java/com/ericsson/eiffel/remrem/publish/config/SecurityConfig.java
Removed based64 encryption mechanism for ldap manager password
> Removed based64 encryption mechanism for ldap manager password

- serviceUsage.html
Added documentation related to jasypt library and its usage
> Added documentation related to jasypt library and usage

- index.html
Updated the document as per the migration from gradle to maven.
> updated the document

- CHANGELOG.md
- pom.xml
- publish-cli/pom.xml
- publish-common/pom.xml
- publish-service/pom.xml
> Updated parent version

- CHANGELOG.md
- pom.xml
- publish-common/pom.xml
updated eiffel remrem parent version from 0.0.5 to 0.0.6.
updated eiffel remrem  shared from 0.3.9 to 0.4.0
updated eiffel remrem semantics from 0.5.0 to 0.5.1
updated amqp-client version  from 5.0.0 to 5.4.0.
###Application Issues
Resolved#124
https://github.com/eiffel-community/eiffel-remrem-publish/issues/123
work with modifications, whether created in whole …
> Resolved#124. Updated eiffelremrem parent,shared,semantics.

- serviceUsage.html
Adding documentation about how to start and configure RemRem-publish when service is executed with java command or maven command.
(c) The contribution was provided …
> Configuration documentation update.

- CHANGELOG.md
- README.md
- pom.xml
- publish-service/src/main/java/com/ericsson/eiffel/remrem/publish/constants/RemremPublishServiceConstants.java
Changed reference links in changelog and readme files from http to https
Also upgraded version from 1.0.0 to 1.0.1.
(c) The contribution was provided directly to me by …
> Changed reference links in changelog and readme files from http to https

- CHANGELOG.md
Updated eiffel-remrem-semantics version in CHANGELOG.md file
person who certified (a), (b) or (c) and I …
> Updated eiffel-remrem-semantics version in CHANGELOG.md file

- CHANGELOG.md
- pom.xml
- publish-common/pom.xml
- publish-common/src/main/java/com/ericsson/eiffel/remrem/publish/config/DecryptionUtils.java
- publish-common/src/main/java/com/ericsson/eiffel/remrem/publish/config/RabbitMqPropertiesConfig.java
Added functionality to decrypt the encrypted properties which are passed from application.properties file.
> Implemented functionality to encrypt open text properties in remrem.

- README.md
- publish-service/src/main/docker/Dockerfile
- publish-service/src/main/docker/README.txt
- publish-service/src/main/docker/health-check.sh
- publish-service/src/main/docker/start-service.sh
- wiki/markdown/docker.md
Adding a Dockerfile so user can build Docker image for Docker and Kubernetes. 
Make it easy to build RemRem-Publish docker images.
(c) The contribution was provided …
> Dockerfile for building images for Docker and Kubernetes.

- CHANGELOG.md
- pom.xml
- publish-cli/pom.xml
- publish-cli/src/main/java/com/ericsson/eiffel/remrem/publish/cli/CLI.java
- publish-cli/src/main/java/com/ericsson/eiffel/remrem/publish/cli/CliOptions.java
- publish-cli/src/test/java/com/ericsson/eiffel/remrem/publish/cli/CliOptionsUnitTests.java
- publish-cli/src/test/java/com/ericsson/eiffel/remrem/publish/cli/CliUnitTests.java
- publish-cli/src/test/resources/publishMessages.json
- publish-common/pom.xml
- publish-common/src/main/java/com/ericsson/eiffel/remrem/publish/config/PropertiesConfig.java
- publish-common/src/main/java/com/ericsson/eiffel/remrem/publish/config/RabbitMqPropertiesConfig.java
- publish-common/src/main/java/com/ericsson/eiffel/remrem/publish/exception/RemRemPublishException.java
- publish-common/src/main/java/com/ericsson/eiffel/remrem/publish/helper/RMQHelper.java
- publish-common/src/main/java/com/ericsson/eiffel/remrem/publish/helper/RabbitMqProperties.java
- publish-common/src/main/java/com/ericsson/eiffel/remrem/publish/service/MessageServiceRMQImpl.java
- publish-common/src/test/java/com/ericsson/eiffel/remrem/publish/helper/RMQHelperUnitTest.java
- publish-service/src/main/java/com/ericsson/eiffel/remrem/publish/controller/ProducerController.java
- publish-service/src/main/resources/application.properties
- publish-service/src/test/java/com/ericsson/eiffel/remrem/publish/integrationtest/EiffelRemRemPublishIT.java
- publish-service/src/test/java/com/ericsson/eiffel/remrem/publish/service/MessageServiceRMQImplUnitTest.java
- publish-service/src/test/resources/expectedParsedEvents/expected_parsed_EiffelActivityStartedEvent.json
- publish-service/src/test/resources/expectedParsedEvents/expected_parsed_EiffelActivityTriggeredEvent.json
Added a createExchangeIfNotExisting property to create an exchange.
For CLI Added a option create_exchange or ce to create exchange.
(c) The contribution was provided …
> Fix for invalid exchange return success message.

- CHANGELOG.md
- pom.xml
- publish-common/src/main/java/com/ericsson/eiffel/remrem/publish/config/RabbitMqPropertiesConfig.java
Made required change in publish-common to fix publish-cli.
> Fixed Publish cli by making code change in publish-common.

- cliUsage.html
- serviceUsage.html
Updated Documentation for Invalid exchange
in REMREM return SUCCESS when trying to
publish a Eiffel Message
Added a new option ce or create exchange to create an exchange if it not available. it is passed as 
command line args for cli (true/false). 
createExchangeIfNotExisting: true or false property is added for both spring and tomcat properties file.
work …
> Updated Documentation gh-pages for Invalid exchange in REMREM return SUCCESS.

- CHANGELOG.md
- pom.xml
- publish-common/src/main/java/com/ericsson/eiffel/remrem/publish/config/RabbitMqPropertiesConfig.java
- publish-common/src/main/java/com/ericsson/eiffel/remrem/publish/service/GenerateURLTemplate.java
- publish-service/src/main/java/com/ericsson/eiffel/remrem/publish/controller/ProducerController.java
- publish-service/src/test/java/com/ericsson/eiffel/remrem/publish/service/EiffelRemremCommonControllerUnitTest.java
Fixed generateAndPublish endpoint to load generate server properties from config.properties file
person who …
> Fixed generateAndPublish endpoint to load generate server properties from config.properties file

- serviceUsage.html
Updated gh-pages for loading application.properties from Tomcat.
> Updated gh-pages for loading application.properties from Tomcat.

- README.md
- pom.xml
- publish-cli/pom.xml
- publish-common/pom.xml
- publish-service/pom.xml
- wiki/markdown/configuration.md
- wiki/markdown/docker.md
- wiki/markdown/running-remrem-publish.md
Today RemRem-Publish fails to read Spring/Java properties from Shell/Cli when Java properties provided with -D flag or other java flags.
This solves so Spring can be configured via -D properties or via providing Spring properties file with Java property flag:
-Dspring.config.location=/path/to/application.properties
With this change we follow the Spring standard configuration:
https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html
RemRem-Publish can now be configure with Spring/Java properties provided with -D flag and other Java flags.
have the right to submit it under the open source …
> Fix Spring and Java properties issues.

- publish-cli/pom.xml
Fixed the main class manifest in war file issue that was introduced in previous version 2.0.4.
person who …
> Fix manifest main class issue in publish cli.

- CHANGELOG.md
- pom.xml
it.
(d) I understand and agree that this …
> Uplifted eiffel-remrem-parent version from 2.0.1 to 2.0.2.

- serviceUsage.html
- statusCodes.html
Updating gh-pages for Lookup properties.
> Updating gh-pages for Lookup properties.

- CHANGELOG.md
- pom.xml
Uplifted eiffel-remrem-semantics version from 2.0.6 to 2.0.7.
person who certified (a), (b) or (c) and I …
> Uplifted eiffel-remrem-semantics version from 2.0.6 to 2.0.7

- CHANGELOG.md
- pom.xml
it.
(d) I understand and agree that this …
> Uplifted eiffel-remrem-semantics version from 2.0.7 to 2.0.8.

- CHANGELOG.md
- pom.xml
Uplifted eiffel-remrem-parent version from 2.0.2 to 2.0.4.
Uplifted eiffel-remrem-shared version from 2.0.2 to 2.0.4.
Uplifted eiffel-remrem-semantics version from 2.0.9 to 2.0.11.
Resolve security vulnerability issue.
permitted to submit under a …
> Uplifted REMReM parent,shared and semantics versions.

- CHANGELOG.md
- publish-cli/src/main/java/com/ericsson/eiffel/remrem/publish/cli/CliOptions.java
- publish-common/src/main/java/com/ericsson/eiffel/remrem/publish/config/PropertiesConfig.java
- publish-common/src/main/java/com/ericsson/eiffel/remrem/publish/config/RabbitMqPropertiesConfig.java
- publish-common/src/main/java/com/ericsson/eiffel/remrem/publish/helper/RabbitMqProperties.java
- publish-common/src/main/resources/config.template.properties
- publish-common/src/test/java/com/ericsson/eiffel/remrem/publish/helper/RMQHelperUnitTest.java
- publish-service/src/main/resources/application.properties
- wiki/markdown/configuration.md
- wiki/markdown/usage/cli.md
- wiki/markdown/usage/service.md
Added new property to customize the rabbitmq channels.
person who certified (a), (b) or (c) and I have not …
> REMReM publish creating lot of AMQP channels

- CHANGELOG.md
- pom.xml
Uplifted eiffel-remrem-semantics version from 2.0.11 to 2.0.12.
person who certified (a), (b) or (c) and I …
> Uplifted eiffel-remrem-semantics version from 2.0.11 to 2.0.12.

- CHANGELOG.md
- pom.xml
Uplifted eiffel-remrem-semantics version from 2.0.12 to 2.0.13.
REMReM is able to accept both a CONTEXT and a CAUSE links in the same event.
(c) The contribution was …
> Uplifted eiffel-remrem-semantics version from 2.0.12 to 2.0.13.

- CHANGELOG.md
- pom.xml
- publish-service/src/main/resources/application.properties
- wiki/markdown/usage/service.md
https://github.com/eiffel-community/eiffel-remrem-publish/issues/192
REMReM Publish: Removed Ericsson specific configuration from GitHub
Keeping the documentation fit for a wider range of users will make it more understandable.
permitted to submit …
> REMReM Publish: Removed Ericsson specific configuration from GitHub.

- CHANGELOG.md
- pom.xml
- publish-service/src/main/java/com/ericsson/eiffel/remrem/publish/controller/ProducerController.java
- publish-service/src/test/java/com/ericsson/eiffel/remrem/publish/service/EiffelRemremCommonControllerUnitTest.java
REMReM publish /generateAndPublish endpoint support to lenient validation
Added lenient validation feature support for /generateAndPublish end point in REMReM publish. …
> REMReM publish /generateAndPublish endpoint support to lenient validation

- CHANGELOG.md
- pom.xml
- publish-common/src/main/java/com/ericsson/eiffel/remrem/publish/service/MessageServiceRMQImpl.java
Modified code changes to handle the error ConcurrentModificationException which occurred when too many requests are sent to /generateAndPublish endpoint.The above issue occurred while iterating ArrayList object by one thread if other thread try to do modification then we will get Runt-time exception saying ConcurrentModificationException by replacing with CopyOnWriteArrayList we are able able to overcome this issue. …
> REMReM publish misbehaves when overloaded

- CHANGELOG.md
- publish-common/src/main/java/com/ericsson/eiffel/remrem/publish/config/RabbitMqPropertiesConfig.java
- publish-service/src/main/java/com/ericsson/eiffel/remrem/publish/controller/ProducerController.java
Implemented changes and made the configurable parameter
"virtualHost" as optional field.
Implemented changes and made the configurable parameter "virtualHost" as optional field.
The parameter will be used only by the required users and will be backward compatible.
by me, under the same open source …
> Made configurable parameter "virtualHost" as optional field.

- CHANGELOG.md
- publish-service/src/main/java/com/ericsson/eiffel/remrem/publish/controller/ProducerController.java
Implemented changes for UTF-8 format problem with REMREM GenerateAndPublish API
Implemented changes for UTF-8 format problem with REMREM GenerateAndPublish API
Swedish characters now wont get translated to unexpected characters.
permitted to …
> UTF-8 format problem with REMReM GenerateAndPublish API

- CHANGELOG.md
- pom.xml
Dummy release for eiffel-remrem-publish as we had some issues with the previous release
person who …
> Dummy release for eiffel-remrem-publish

- CHANGELOG.md
- pom.xml
https://github.com/eiffel-community/eiffel-remrem-publish/issues/243
- Updated remrem-parent from 2.0.7 to 2.0.8
- Uplifted remrem-semantics from 2.2.2 to 2.2.3
(c) The …
> Updated remrem-parent from 2.0.7 to 2.0.8 and remrem-semantics from 2.2.2 to 2.2.3

- CHANGELOG.md
- pom.xml
- publish-common/src/main/java/com/ericsson/eiffel/remrem/publish/helper/RabbitMqProperties.java
Made the changes to overide the AMQP Basic properties.
person who certified (a), (b) or (c) and I have not …
> Overide the AMQP Basic Properties

- CHANGELOG.md
- publish-common/src/main/java/com/ericsson/eiffel/remrem/publish/helper/RabbitMqProperties.java
https://github.com/eiffel-community/eiffel-remrem-publish/issues/244
Added a code changes to recover/recreate a new channel when it is closed.
(c) The contribution was …
> Made changes to create a new channel when it is closed while publishing

- wiki/markdown/index.md
Resolves eiffel-community/eiffel-remrem#10
Adds a compatibility table between generate and publish services.
Makes live of user easier.
(c) The contribution was provided …
> Compatibility between generate and publish

- wiki/markdown/logging.md
Fixes #267
Fixes #268
Non-existing link removed from documentation
person who certified (a), (b) or (c) and …
> Documentation contains broken link and bogus example

- publish-common/src/main/java/com/ericsson/eiffel/remrem/publish/helper/RabbitMqProperties.java
When a connection to MB channel is closed, the cause of connection close is described properly in the log file.
The connection close cause is available now. 
(c) The …
> Make log record on 'channel closed' more verbose

- CHANGELOG.md
- publish-common/pom.xml
Uplifted the amqp-client version to 5.20.0
it. …
> Uplifted the amqp-client version to 5.20.0

- publish-service/src/main/java/com/ericsson/eiffel/remrem/publish/config/CustomAuthenticationEntryPoint.java
An authentication popup window is displayed when an endpoint requiring authenication is accessed from a web browser.
HTTP header WWW-Authenticate:Basic is sent to requester when insufficient authentication is detected.
permitted to submit under a …
> Open authentication popup window when in a web browser

- publish-service/src/main/java/com/ericsson/eiffel/remrem/publish/App.java
Log file catalina.out contains the information related to password used by spring-boot
The records related to generated password no more appear in catalina.out.
(c) The …
> The records related to generated password no more appear in catalina.out

- pom.xml
Updated the publish version in pom file according to the latest release.
person who certified (a), (b) or …
> Updated the publish version in pom file

- pom.xml
Release version increased in pom.xml.
it.
(d) …
> Sync release version with release tag

- pom.xml
- publish-common/src/main/java/com/ericsson/eiffel/remrem/publish/service/EventTemplateHandler.java
Fixes https://github.com/eiffel-community/eiffel-remrem/issues/14
person who certified (a), (b) or (c) and …
> Orizaba is default Eiffel protocol

- .github/workflows/main.yml
- README.md
Update code coverage with coveralls and build badge with github actions
person who certified (a), (b) or …
> Update code coverage with coveralls and build badge with github actions

- pom.xml
- publish-cli/pom.xml
- publish-common/pom.xml
- publish-service/pom.xml
- publish-service/src/main/java/com/ericsson/eiffel/remrem/publish/config/SwaggerConfig.java
- publish-service/src/main/java/com/ericsson/eiffel/remrem/publish/controller/RemremHomeController.java
Uplift swagger to 3.0.0
it.
(d) I understand …
> Uplift swagger to 3.0.0
